import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
  version: 9,
  tables: [
    tableSchema({
      name: 'users',
      columns: [
        { name: 'convex_user_id', type: 'string', isIndexed: true },
        // camelCase mirrors for Convex alignment (added in v6)
        { name: 'convexUserId', type: 'string', isOptional: true, isIndexed: true },
        { name: 'email', type: 'string' },
        { name: 'first_name', type: 'string' },
        { name: 'last_name', type: 'string' },
        { name: 'has_completed_onboarding', type: 'boolean' },
        { name: 'email_verification_time', type: 'number', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'phone_verification_time', type: 'number', isOptional: true },
        { name: 'is_anonymous', type: 'boolean', isOptional: true },
        { name: 'name', type: 'string', isOptional: true },
        { name: 'image', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        // camelCase mirrors for Convex alignment (added in v6)
        { name: 'firstName', type: 'string', isOptional: true },
        { name: 'lastName', type: 'string', isOptional: true },
        { name: 'hasCompletedOnboarding', type: 'boolean', isOptional: true },
        { name: 'emailVerificationTime', type: 'number', isOptional: true },
        { name: 'phoneVerificationTime', type: 'number', isOptional: true },
        { name: 'isAnonymous', type: 'boolean', isOptional: true },
        { name: 'createdAt', type: 'number', isOptional: true },
        { name: 'updatedAt', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'user_profiles',
      columns: [
        { name: 'userId', type: 'string', isIndexed: true },
        { name: 'address1', type: 'string', isOptional: true },
        { name: 'address2', type: 'string', isOptional: true },
        { name: 'age', type: 'string', isOptional: true },
        { name: 'ageRange', type: 'string', isOptional: true },
        { name: 'allergies', type: 'string', isOptional: true },
        { name: 'city', type: 'string', isOptional: true },
        { name: 'createdAt', type: 'number' },
        { name: 'currentMedications', type: 'string', isOptional: true },
        { name: 'emergencyContactName', type: 'string', isOptional: true },
        { name: 'emergencyContactPhone', type: 'string', isOptional: true },
        { name: 'location', type: 'string', isOptional: true },
        { name: 'locationServicesEnabled', type: 'boolean', isOptional: true },
        { name: 'medicalConditions', type: 'string', isOptional: true },
        { name: 'onboardingCompleted', type: 'boolean' },
        { name: 'postalCode', type: 'string', isOptional: true },
        { name: 'province', type: 'string', isOptional: true },
        { name: 'reminders', type: 'string', isOptional: true },
        { name: 'symptomReminderDayOfWeek', type: 'string', isOptional: true },
        { name: 'symptomReminderEnabled', type: 'boolean', isOptional: true },
        { name: 'symptomReminderFrequency', type: 'string', isOptional: true },
        { name: 'symptomReminderTime', type: 'string', isOptional: true },
        { name: 'updatedAt', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'health_entries',
      columns: [
        { name: 'userId', type: 'string', isIndexed: true },
        { name: 'convexId', type: 'string', isIndexed: true, isOptional: true },
        { name: 'date', type: 'string' },
        { name: 'timestamp', type: 'number' },
        { name: 'symptoms', type: 'string' },
        { name: 'severity', type: 'number' },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'duration', type: 'string', isOptional: true },
        { name: 'aiContext', type: 'string', isOptional: true },
        { name: 'photos', type: 'string', isOptional: true }, // Store as JSON string
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'createdBy', type: 'string' },
        { name: 'type', type: 'string', isOptional: true },
        { name: 'isSynced', type: 'boolean' },
        { name: 'syncError', type: 'string', isOptional: true },
        { name: 'createdAt', type: 'number' },
        { name: 'updatedAt', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'medical_facilities',
      columns: [
        { name: 'facility_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'address', type: 'string' },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'hours', type: 'string', isOptional: true },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'distance', type: 'number' },
        { name: 'distance_text', type: 'string' },
        { name: 'source', type: 'string' },
        { name: 'user_location', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'reminders',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'reminder_id', type: 'string', isIndexed: true },
        { name: 'enabled', type: 'boolean' },
        { name: 'frequency', type: 'string' },
        { name: 'time', type: 'string', isOptional: true },
        { name: 'day_of_week', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        // camelCase mirrors for Convex alignment (added in v7)
        { name: 'userId', type: 'string', isOptional: true, isIndexed: true },
        { name: 'reminderId', type: 'string', isOptional: true, isIndexed: true },
        { name: 'dayOfWeek', type: 'string', isOptional: true },
        { name: 'createdAt', type: 'number', isOptional: true },
        { name: 'updatedAt', type: 'number', isOptional: true },
      ],
    }),
  ],
});